# Generated by Django 3.2.16 on 2022-10-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='almacenado_AZ',
            field=models.CharField(choices=[('1. Vice Docencia', (('1.1. Oficios', '1.1. Oficios'), ('1.2. Citaciones-Circulares-Memorandos', '1.2. Citaciones-Circulares-Memorandos'), ('1.2. Certificados', '1.2. Certificados'))), ('2. SecretarGeneral', (('2.1. Oficios', '2.1. Oficios'), ('2.2. Comisiones', '2.2. Comisiones'), ('2.3. PQRS', '2.3. PQRS'))), ('3. Consejos', (('3.1. Acuerdo CS', '3.1. Acuerdo CS'), ('3.2. Resoluciones CS', '3.2. Resoluciones CS'), ('3.3. Acuerdos CA', '3.3. Acuerdos CA'), ('3.4. Resoluciones CA', '3.4. Resoluciones CA'), ('3.5. Actas CA', '3.5. Actas CA'))), ('4. Oficinas Asesoras de Jur y Control Disciplinario', (('4.1. Oficios Jur', '4.1. Oficios Jur'), ('4.2. Conceptos Jur', '4.2. Conceptos Jur'), ('4.3. Oficios CD ', '4.3. Oficios CD '))), ('5. Oficina Asesora de GestiHumana y Desarrollo de Personal', (('5.1. GestiHumana', '5.1. GestiHumana'), ('5.2. Personal', '5.2. Personal'), ('5.3. Desarrollo Organizacional', '5.3. Desarrollo Organizacional'))), ('6. Rectory Vicerector', (('6.1. Rector', '6.1. Rector'), ('6.2. Vice-Administrativa', '6.2. Vice-Administrativa'), ('6.3. Vice-Bienestar', '6.3. Vice-Bienestar'), ('6.4. Vice-Calidad', '6.4. Vice-Calidad'), ('6.5. Vice-Extension', '6.5. Vice-Extension'), ('6.6. Vice-Internacionalizaci', '6.6. Vice-Internacionalizaci'), ('6.7. Vice-Investigaci', '6.7. Vice-Investigaci'))), ('7. Oficina Asesoras de Planeaci y Control Interno', (('7.1. Oficios P', '7.1. Oficios P'), ('7.2. Oficios CI', '7.2. Oficios CI'))), ('8. AuditorControl Interno', (('8.1. AuditorCI', '8.1. AuditorCI'),)), ('9. Facultades Centro', (('9.1. Fac. C. Humanas', '9.1. Fac. C. Humanas'), ('9.2. Fac. C. Sociales', '9.2. Fac. C. Sociales'), ('9.3. Fac. Derecho', '9.3. Fac. Derecho'))), ('10. Facultades Piedra', (('10.1. Fac. C. Econ', '10.1. Fac. C. Econ'), ('10.2. Fac. C. Exactas y Naturales', '10.2. Fac. C. Exactas y Naturales'), ('10.3. Fac. Ingenier', '10.3. Fac. Ingenier'))), ('11. Facultades Salud', (('11.1. Fac. C. Farmac', '11.1. Fac. C. Farmac'), ('11.2. Fac. Enfermer', '11.2. Fac. Enfermer'), ('11.3. Fac. Medicina', '11.3. Fac. Medicina'), ('11.4. Fac. Odontolog', '11.4. Fac. Odontolog'))), ('12. Institutos', (('12.1. Inst. Inmunolog', '12.1. Inst. Inmunolog'), ('12.2. Inst. Hidr', '12.2. Inst. Hidr'), ('12.3 Inst. Estudios del Caribe', '12.3 Inst. Estudios del Caribe'), ('12.4. Inst. MatemAplicada', '12.4. Inst. MatemAplicada'), ('12.5. Inst. PolPublicas IPREG', '12.5. Inst. PolPublicas IPREG'))), ('13. Rutas Acady Salidas de Campo', (('13.1. Rutas Acad', '13.1. Rutas Acad'), ('13.2. Salidas de Campo', '13.2. Salidas de Campo'))), ('14. Otras Oficinas Internas', '14. Otras Oficinas Internas'), ('15. Correspondencia Externa', '15. Correspondencia Externa'), ('16. Solicitud de Docentes', '16. Solicitud de Docentes'), ('17. Correos electr', '17. Correos electr'), ('18. Informe de gesti', '18. Informe de gesti'), ('19. Centros', (('19.1. C. de admisiones', '19.1. C. de admisiones'), ('19.2. C. de autoevaluaci', '19.2. C. de autoevaluaci'), ('19.3  C. de informaciy D.', '19.3  C. de informaciy D.'), ('19.4. C. de inform', '19.4. C. de inform'), ('19.5. C. de postgrado', '19.5. C. de postgrado')))], max_length=100),
        ),
    ]
