# Generated by Django 4.2.4 on 2023-08-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0003_auto_20221121_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
